#!/bin/bash

echo "=== WSL DNS Fix Script ==="
echo "This script will guide you through fixing WSL DNS issues"
echo ""

echo "STEP 1: Modify /etc/wsl.conf"
echo "Run this command:"
echo "sudo nano /etc/wsl.conf"
echo ""
echo "Add these lines to the end of the file:"
echo "[network]"
echo "generateResolvConf = false"
echo ""
echo "Your complete file should look like:"
echo "[boot]"
echo "systemd=true"
echo ""
echo "[user]"
echo "default=brian"
echo ""
echo "[network]"
echo "generateResolvConf = false"
echo ""

echo "STEP 2: Shutdown WSL"
echo "Open Windows PowerShell/Command Prompt and run:"
echo "wsl --shutdown"
echo ""

echo "STEP 3: Set DNS servers"
echo "After restarting WSL, run:"
echo "sudo nano /etc/resolv.conf"
echo ""
echo "Replace all content with:"
echo "nameserver 8.8.8.8"
echo "nameserver 1.1.1.1"
echo ""

echo "=== Current Status ==="
echo "Current DNS server: $(cat /etc/resolv.conf | grep nameserver | head -1)"
echo "WSL config exists: $([ -f /etc/wsl.conf ] && echo 'Yes' || echo 'No')"