#!/usr/bin/env python3
"""
KGAS Quick Setup

Simple setup script for KGAS system. Creates configuration files
with sensible defaults and guides through basic setup.
"""

import os
import sys
import secrets
import string
from pathlib import Path

def generate_password(length=16):
    """Generate a secure password"""
    alphabet = string.ascii_letters + string.digits + "!@#$%^&*"
    return ''.join(secrets.choice(alphabet) for _ in range(length))

def create_env_file():
    """Create .env file with configuration"""
    print("🔧 Creating .env configuration file...")
    
    # Check if .env already exists
    if Path(".env").exists():
        response = input("   .env file already exists. Overwrite? [y/N]: ").strip().lower()
        if response not in ["y", "yes"]:
            print("   Keeping existing .env file")
            return True
    
    # Get basic configuration
    print("\n📝 Basic Configuration:")
    neo4j_uri = input("   Neo4j URI [bolt://localhost:7687]: ").strip() or "bolt://localhost:7687"
    neo4j_user = input("   Neo4j username [neo4j]: ").strip() or "neo4j"
    
    # Generate secure password
    use_generated_password = input("   Generate secure Neo4j password? [Y/n]: ").strip().lower()
    if use_generated_password in ["", "y", "yes"]:
        neo4j_password = generate_password(16)
        print(f"   Generated password: {neo4j_password}")
    else:
        neo4j_password = input("   Neo4j password: ").strip()
    
    # Create .env content
    env_content = f"""# KGAS Configuration
# Generated by KGAS Quick Setup
# Keep this file secure and do not commit to version control

# Environment
KGAS_ENV=development
KGAS_LOG_LEVEL=INFO

# Neo4j Database
NEO4J_URI={neo4j_uri}
NEO4J_USER={neo4j_user}
NEO4J_PASSWORD={neo4j_password}

# System Settings
KGAS_MAX_WORKERS=4
KGAS_DEBUG=true
KGAS_METRICS_ENABLED=true

# Optional: LLM API Keys (uncomment and set if needed)
# OPENAI_API_KEY=your-openai-key-here
# ANTHROPIC_API_KEY=your-anthropic-key-here
# GOOGLE_API_KEY=your-google-key-here

# Optional: Custom paths
# KGAS_DATA_DIR=./data
# KGAS_LOGS_DIR=./logs
# KGAS_CONFIG_DIR=./config
"""
    
    # Write .env file
    with open(".env", "w") as f:
        f.write(env_content)
    
    print("   ✅ Created .env file")
    return True

def create_gitignore():
    """Ensure .env is in .gitignore"""
    gitignore_path = Path(".gitignore")
    
    # Read existing .gitignore
    existing_content = ""
    if gitignore_path.exists():
        with open(gitignore_path, "r") as f:
            existing_content = f.read()
    
    # Check if .env is already ignored
    if ".env" in existing_content:
        return True
    
    # Add .env to .gitignore
    with open(gitignore_path, "a") as f:
        if existing_content and not existing_content.endswith("\n"):
            f.write("\n")
        f.write("\n# KGAS Environment Configuration\n.env\n.env.*\n")
    
    print("   ✅ Added .env to .gitignore")
    return True

def create_config_directory():
    """Create config directory with basic template"""
    config_dir = Path("config")
    config_dir.mkdir(exist_ok=True)
    
    # Create basic config template if it doesn't exist
    default_config = config_dir / "default.yaml"
    if not default_config.exists():
        config_content = """# KGAS Default Configuration
api:
  anthropic_api_key: '${ANTHROPIC_API_KEY:-}'
  google_api_key: '${GOOGLE_API_KEY:-}'
  max_retries: 3
  openai_api_key: '${OPENAI_API_KEY:-}'
  timeout: 30

llm:
  primary_model: "gpt_4o_mini"
  fallback_models:
    - "gemini_flash" 
    - "claude_sonnet_4"
  timeout_seconds: 30
  max_retries: 3
  fallback_on_rate_limit: true
  fallback_on_timeout: true
  fallback_on_error: true

database:
  database: neo4j
  host: '${NEO4J_HOST:-localhost}'
  password: '${NEO4J_PASSWORD}'
  port: '${NEO4J_PORT:-7687}'
  username: '${NEO4J_USER:-neo4j}'

system:
  backup_enabled: false
  encryption_enabled: false
  log_level: '${KGAS_LOG_LEVEL:-INFO}'
  max_workers: '${KGAS_MAX_WORKERS:-4}'
  metrics_enabled: true
"""
        
        with open(default_config, "w") as f:
            f.write(config_content)
        
        print("   ✅ Created config/default.yaml")
    
    return True

def test_configuration():
    """Test the configuration"""
    print("\n🧪 Testing configuration...")
    
    try:
        # Load environment
        from dotenv import load_dotenv
        load_dotenv()
        
        # Check required variables
        required_vars = ["NEO4J_URI", "NEO4J_USER", "NEO4J_PASSWORD"]
        missing = [var for var in required_vars if not os.getenv(var)]
        
        if missing:
            print(f"   ❌ Missing required variables: {', '.join(missing)}")
            return False
        
        # Try Neo4j connection
        try:
            from neo4j import GraphDatabase
            
            uri = os.getenv("NEO4J_URI")
            user = os.getenv("NEO4J_USER")
            password = os.getenv("NEO4J_PASSWORD")
            
            driver = GraphDatabase.driver(uri, auth=(user, password))
            with driver.session() as session:
                session.run("RETURN 1")
            driver.close()
            
            print("   ✅ Neo4j connection successful")
            return True
            
        except ImportError:
            print("   ⚠️  Neo4j driver not installed (pip install neo4j)")
            print("   ✅ Configuration file created successfully")
            return True
        except Exception as e:
            print(f"   ⚠️  Neo4j connection failed: {e}")
            print("   ✅ Configuration file created (check Neo4j settings)")
            return True
            
    except ImportError:
        print("   ⚠️  python-dotenv not installed (pip install python-dotenv)")
        print("   ✅ Configuration file created")
        return True
    except Exception as e:
        print(f"   ❌ Configuration test failed: {e}")
        return False

def show_next_steps():
    """Show next steps"""
    print("\n🚀 Setup Complete! Next Steps:")
    print("   1. Install dependencies: pip install -r requirements.txt")
    print("   2. Start Neo4j database (if not running)")
    print("   3. Verify setup: python scripts/verify_config.py")
    print("   4. Run KGAS tools: python src/mcp_server.py")
    print("\n📚 Documentation:")
    print("   • Check SETUP_GUIDE.md for detailed setup instructions")
    print("   • Run python scripts/setup_config.py for advanced setup")
    print("   • Edit .env file to customize configuration")

def main():
    """Main setup function"""
    print("🎯 KGAS Quick Setup")
    print("=" * 30)
    print("This will create basic configuration files for KGAS.")
    print()
    
    try:
        # Create configuration files
        if not create_env_file():
            return 1
        
        create_gitignore()
        create_config_directory()
        
        # Test configuration
        if not test_configuration():
            print("\n⚠️  Configuration created but testing failed")
            print("   Please check your settings and try running:")
            print("   python scripts/verify_config.py")
        
        show_next_steps()
        return 0
        
    except KeyboardInterrupt:
        print("\n❌ Setup cancelled")
        return 1
    except Exception as e:
        print(f"\n❌ Setup failed: {e}")
        return 1

if __name__ == "__main__":
    sys.exit(main())