"""
Entity ID Preserving T31 Entity Builder

Modified version of T31 that preserves entity IDs from T23c to maintain provenance chain.
"""

from typing import Dict, List, Any, Optional
import logging
from src.tools.phase1.t31_entity_builder_unified import T31EntityBuilderUnified

logger = logging.getLogger(__name__)


class T31EntityBuilderPreservingIDs(T31EntityBuilderUnified):
    """
    Entity builder that preserves entity IDs from upstream tools.
    
    This maintains the provenance chain by using the entity IDs
    generated by T23c instead of creating new ones.
    """
    
    def _group_mentions_by_entity(self, mentions: List[Dict[str, Any]]) -> Dict[str, List[Dict[str, Any]]]:
        """
        Group mentions by entity, preserving upstream entity IDs.
        
        Key difference: Uses entity_id from mentions if available,
        only generates new IDs as a fallback.
        """
        entity_groups = {}
        id_mapping = {}  # Maps generated IDs to provided IDs
        
        for mention in mentions:
            # Check if mention already has an entity_id from upstream
            provided_entity_id = mention.get("entity_id")
            
            if provided_entity_id:
                # Use the provided entity ID
                entity_id = provided_entity_id
                self.logger.debug(f"Preserving upstream entity_id: {entity_id}")
            else:
                # Only generate ID if not provided
                text = mention.get("text", "").strip().lower()
                entity_type = mention.get("entity_type", "UNKNOWN")
                generated_id = f"{entity_type}_{hash(text) % 10000:04d}"
                
                # Check if we've seen this generated ID before
                if generated_id in id_mapping:
                    entity_id = id_mapping[generated_id]
                else:
                    # Use generated ID as fallback
                    entity_id = generated_id
                    self.logger.warning(
                        f"No entity_id provided for mention '{text}', "
                        f"using generated ID: {entity_id}"
                    )
                
                mention["entity_id"] = entity_id
            
            # Group mentions by entity ID
            if entity_id not in entity_groups:
                entity_groups[entity_id] = []
            entity_groups[entity_id].append(mention)
            
            # Track ID mappings for consistency
            if not provided_entity_id and entity_id not in id_mapping:
                id_mapping[generated_id] = entity_id
        
        self.logger.info(
            f"Grouped {len(mentions)} mentions into {len(entity_groups)} entities, "
            f"{sum(1 for m in mentions if m.get('entity_id'))} with preserved IDs"
        )
        
        return entity_groups
    
    def _build_single_entity(
        self, 
        entity_id: str, 
        mentions: List[Dict[str, Any]], 
        source_refs: List[str]
    ) -> Optional[Dict[str, Any]]:
        """
        Build a single entity, preserving the entity ID for provenance.
        """
        # Log provenance information
        self.logger.info(
            f"Building entity {entity_id} from {len(mentions)} mentions, "
            f"sources: {source_refs}"
        )
        
        # Call parent implementation
        entity = super()._build_single_entity(entity_id, mentions, source_refs)
        
        if entity:
            # Ensure entity_id is preserved in the result
            entity["entity_id"] = entity_id
            
            # Add provenance metadata
            entity["provenance"] = {
                "original_entity_id": entity_id,
                "mention_count": len(mentions),
                "source_refs": source_refs,
                "builder_version": "id_preserving_v1"
            }
        
        return entity
    
    def execute(self, request):
        """
        Execute entity building while preserving entity IDs.
        
        Logs detailed provenance information for debugging.
        """
        self.logger.info(
            f"T31 Entity Builder (ID Preserving) executing with "
            f"{len(request.input_data.get('mentions', []))} mentions"
        )
        
        # Log incoming entity IDs
        mentions = request.input_data.get("mentions", [])
        entity_ids = [m.get("entity_id") for m in mentions if m.get("entity_id")]
        if entity_ids:
            self.logger.info(f"Received {len(entity_ids)} mentions with entity IDs")
            self.logger.debug(f"Entity IDs: {entity_ids[:5]}...")  # Show first 5
        else:
            self.logger.warning("No mentions have entity_id - will generate new IDs")
        
        # Execute parent implementation
        result = super().execute(request)
        
        # Log results
        if result.status == "success":
            entity_count = result.data.get("entity_count", 0)
            self.logger.info(
                f"Successfully created {entity_count} entities with preserved IDs"
            )
        
        return result


def test_id_preservation():
    """Test that entity IDs are preserved through the pipeline."""
    from src.core.service_manager import ServiceManager
    from src.tools.base_tool import ToolRequest
    
    service_manager = ServiceManager()
    builder = T31EntityBuilderPreservingIDs(service_manager)
    
    # Test data with entity IDs from T23c
    mentions = [
        {
            "mention_id": "mention_001",
            "text": "Dr. Jane Smith",
            "entity_type": "PERSON",
            "entity_id": "entity_abc123",  # ID from T23c
            "confidence": 0.9,
            "source_ref": "doc_001"
        },
        {
            "mention_id": "mention_002",
            "text": "Jane Smith",
            "entity_type": "PERSON",
            "entity_id": "entity_abc123",  # Same entity
            "confidence": 0.85,
            "source_ref": "doc_001"
        },
        {
            "mention_id": "mention_003",
            "text": "TechCorp",
            "entity_type": "ORG",
            "entity_id": "entity_xyz789",  # Different entity
            "confidence": 0.95,
            "source_ref": "doc_001"
        }
    ]
    
    request = ToolRequest(
        tool_id="T31_ENTITY_BUILDER",
        operation="build_entities",
        input_data={
            "mentions": mentions,
            "source_refs": ["doc_001"]
        }
    )
    
    result = builder.execute(request)
    
    if result.status == "success":
        print(f"Created {result.data['entity_count']} entities")
        
        # Check if entity IDs were preserved in Neo4j
        from neo4j import GraphDatabase
        driver = GraphDatabase.driver("bolt://localhost:7687", auth=("neo4j", "password"))
        
        with driver.session() as session:
            # Query for our specific entity IDs
            query = """
            MATCH (e:Entity)
            WHERE e.entity_id IN ['entity_abc123', 'entity_xyz789']
            RETURN e.entity_id as id, e.canonical_name as name
            """
            results = session.run(query).data()
            
            print("\nPreserved entities in Neo4j:")
            for r in results:
                print(f"  - {r['id']}: {r['name']}")
        
        driver.close()
    else:
        print(f"Error: {result.error_message}")


if __name__ == "__main__":
    test_id_preservation()